[tool.poetry]
name = "healthy"
version = "0.1.0"
description = ""
authors = ["Marius S <39998+winding-lines@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
